"""Added table to add telegram_file <> bot_token relation

Revision ID: 6251223b7a77
Revises: 76e388cb011b
Create Date: 2019-12-25 03:38:57.497484

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6251223b7a77'
down_revision = '76e388cb011b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hashed_token', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_bot_tokens_hashed_token'), 'bot_tokens', ['hashed_token'], unique=True)
    op.create_table('association',
                    sa.Column('bot_token_id', sa.Integer(), nullable=True),
                    sa.Column('telegram_file_id_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['bot_token_id'], ['bot_tokens.id'], ),
                    sa.ForeignKeyConstraint(['telegram_file_id_id'], ['telegram_file_ids.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_index(op.f('ix_bot_tokens_hashed_token'), table_name='bot_tokens')
    op.drop_table('bot_tokens')
    # ### end Alembic commands ###
