"""Removed unnecessary index

Revision ID: 8c7e750c5f11
Revises: 6251223b7a77
Create Date: 2020-02-12 01:50:52.357259

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '8c7e750c5f11'
down_revision = '6251223b7a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bot_tokens_hashed_token', table_name='bot_tokens')
    op.create_unique_constraint(None, 'bot_tokens', ['hashed_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bot_tokens', type_='unique')
    op.create_index('ix_bot_tokens_hashed_token', 'bot_tokens', ['hashed_token'], unique=True)
    # ### end Alembic commands ###
