"""added indexes to url, telegram_file_id and image_hash columns

Revision ID: a7b7c2c9b5c2
Revises: ee05ae1a75b1
Create Date: 2019-06-23 02:14:13.417581

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a7b7c2c9b5c2'
down_revision = 'ee05ae1a75b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_images_image_hash'), 'images', ['image_hash'], unique=False)
    op.create_index(op.f('ix_images_telegram_file_id'), 'images', ['telegram_file_id'], unique=False)
    op.create_index(op.f('ix_images_url'), 'images', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_url'), table_name='images')
    op.drop_index(op.f('ix_images_telegram_file_id'), table_name='images')
    op.drop_index(op.f('ix_images_image_hash'), table_name='images')
    # ### end Alembic commands ###
