"""added image_data and image_hash columns

Revision ID: ee05ae1a75b1
Revises: 
Create Date: 2019-06-17 00:20:13.118843

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ee05ae1a75b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('images', sa.Column('image_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'image_hash')
    op.drop_column('images', 'image_data')
    # ### end Alembic commands ###
